/**
 * JAIC PDF Report Generator
 * Professional investigational report generation system
 * Attorney Work Product - Confidential
 *
 * @requires puppeteer (npm install puppeteer)
 * @usage import { generateInvestigationalReport } from '@/lib/pdf-generator'
 */

import type { CaseNumber, CaseDomain } from './case-number';
import type { ChainOfCustodyEntry } from './chain-of-custody';
import { verifyCustodyChain } from './chain-of-custody';

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

export interface EvidenceItem {
  id: string;
  fileName: string;
  fileType: string;
  fileSize: number;
  uploadDate: string;
  hash: string;
  verificationStatus: 'VERIFIED' | 'UNVERIFIED' | 'FAILED';
  description?: string;
  metadata?: Record<string, unknown>;
}

export interface TimelineEvent {
  timestamp: string;
  event: string;
  actor: string;
  description: string;
  category: 'STATUS_CHANGE' | 'EVIDENCE_ADDED' | 'ACTION_TAKEN' | 'NOTE_ADDED';
}

export interface CaseData {
  // Case Identification
  caseNumber: CaseNumber;
  title: string;
  domain: CaseDomain;
  status: 'INTAKE' | 'ACTIVE' | 'PENDING' | 'CLOSED' | 'ARCHIVED';

  // Dates
  intakeDate: string;
  lastModified: string;
  closedDate?: string;

  // Client Information
  client?: {
    name: string;
    organization?: string;
    contactInfo?: string;
    referenceNumber?: string;
  };

  // Executive Summary
  executiveSummary: {
    overview: string;
    keyFindings: string[];
    recommendations: string[];
  };

  // Evidence
  evidence: EvidenceItem[];

  // Chain of Custody
  chainOfCustody: ChainOfCustodyEntry[];

  // Timeline
  timeline: TimelineEvent[];

  // Additional Information
  notes?: string;
  metadata?: Record<string, unknown>;
}

export interface ReportOptions {
  includeClientInfo?: boolean;
  includeEvidence?: boolean;
  includeChainOfCustody?: boolean;
  includeTimeline?: boolean;
  watermark?: boolean;
  classification?: string;
}

// ============================================================================
// HTML TEMPLATE GENERATOR
// ============================================================================

function generateHTMLReport(data: CaseData, options: ReportOptions = {}): string {
  const {
    includeClientInfo = true,
    includeEvidence = true,
    includeChainOfCustody = true,
    includeTimeline = true,
    watermark = true,
    classification = 'CONFIDENTIAL - ATTORNEY WORK PRODUCT'
  } = options;

  const generatedDate = new Date().toISOString();
  const formattedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const custodyVerification = verifyCustodyChain(data.chainOfCustody);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JAIC Investigational Brief - ${data.caseNumber.full}</title>
  <style>
    /* ============================================================ */
    /* JAIC Professional Report Styling */
    /* ============================================================ */

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    @page {
      size: letter;
      margin: 0.75in 0.75in 1in 0.75in;

      @bottom-left {
        content: "${data.caseNumber.full}";
        font-family: 'Courier New', monospace;
        font-size: 8pt;
        color: #666;
      }

      @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-family: 'Courier New', monospace;
        font-size: 8pt;
        color: #666;
      }

      @bottom-right {
        content: "${new Date().toISOString().split('T')[0]}";
        font-family: 'Courier New', monospace;
        font-size: 8pt;
        color: #666;
      }
    }

    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a1a;
      background: white;
    }

    ${watermark ? `
    body::before {
      content: "GENERATED BY JAIC INVESTIGATIONAL SYSTEM";
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) rotate(-45deg);
      font-size: 72pt;
      font-weight: bold;
      color: rgba(0, 0, 0, 0.03);
      z-index: -1;
      white-space: nowrap;
      pointer-events: none;
    }
    ` : ''}

    .page {
      page-break-after: always;
      min-height: 9.5in;
    }

    .page:last-child {
      page-break-after: avoid;
    }

    /* Cover Page */
    .cover-page {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
      min-height: 9.5in;
      padding: 2in 1in;
    }

    .logo {
      font-family: 'Courier New', monospace;
      font-size: 32pt;
      font-weight: bold;
      letter-spacing: 8px;
      margin-bottom: 0.5in;
      color: #1a1a1a;
      border: 4px solid #1a1a1a;
      padding: 20px 40px;
    }

    .report-title {
      font-size: 24pt;
      font-weight: bold;
      margin: 0.5in 0 0.25in 0;
      text-transform: uppercase;
      letter-spacing: 2px;
    }

    .case-number {
      font-family: 'Courier New', monospace;
      font-size: 18pt;
      font-weight: bold;
      margin: 0.25in 0;
      letter-spacing: 2px;
      color: #333;
    }

    .classification {
      font-family: 'Courier New', monospace;
      font-size: 14pt;
      font-weight: bold;
      color: #c00;
      margin: 0.5in 0;
      padding: 20px;
      border: 3px solid #c00;
      text-transform: uppercase;
      letter-spacing: 1px;
    }

    .date-generated {
      font-size: 12pt;
      color: #666;
      margin: 0.25in 0;
    }

    .prepared-by {
      font-size: 11pt;
      color: #333;
      margin-top: 1in;
      font-style: italic;
    }

    /* Section Headers */
    h1 {
      font-size: 18pt;
      font-weight: bold;
      margin: 0.4in 0 0.2in 0;
      padding-bottom: 0.1in;
      border-bottom: 3px solid #1a1a1a;
      text-transform: uppercase;
      letter-spacing: 1px;
      page-break-after: avoid;
    }

    h2 {
      font-size: 14pt;
      font-weight: bold;
      margin: 0.3in 0 0.15in 0;
      color: #333;
      page-break-after: avoid;
    }

    h3 {
      font-size: 12pt;
      font-weight: bold;
      margin: 0.2in 0 0.1in 0;
      color: #555;
      page-break-after: avoid;
    }

    /* Content Elements */
    p {
      margin: 0.1in 0;
      text-align: justify;
    }

    ul, ol {
      margin: 0.1in 0 0.1in 0.3in;
    }

    li {
      margin: 0.05in 0;
      page-break-inside: avoid;
    }

    /* Tables */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 0.15in 0;
      font-size: 10pt;
      page-break-inside: avoid;
    }

    th {
      background: #1a1a1a;
      color: white;
      font-weight: bold;
      text-align: left;
      padding: 8px 12px;
      border: 1px solid #1a1a1a;
      font-size: 9pt;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    td {
      padding: 6px 12px;
      border: 1px solid #ccc;
      vertical-align: top;
    }

    tr:nth-child(even) {
      background: #f9f9f9;
    }

    /* Info Boxes */
    .info-box {
      background: #f5f5f5;
      border-left: 4px solid #1a1a1a;
      padding: 0.15in;
      margin: 0.15in 0;
      page-break-inside: avoid;
    }

    .info-box strong {
      display: inline-block;
      min-width: 150px;
      font-family: 'Courier New', monospace;
      font-size: 10pt;
    }

    .warning-box {
      background: #fff8dc;
      border: 2px solid #ff8c00;
      padding: 0.15in;
      margin: 0.15in 0;
      font-weight: bold;
    }

    .error-box {
      background: #ffe4e4;
      border: 2px solid #c00;
      padding: 0.15in;
      margin: 0.15in 0;
      color: #c00;
      font-weight: bold;
    }

    .success-box {
      background: #e8f5e9;
      border: 2px solid #4caf50;
      padding: 0.15in;
      margin: 0.15in 0;
      color: #2e7d32;
    }

    /* Code/Hash Display */
    .code {
      font-family: 'Courier New', monospace;
      background: #f5f5f5;
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 9pt;
      word-break: break-all;
    }

    /* Status Badges */
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 9pt;
      font-weight: bold;
      font-family: 'Courier New', monospace;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .badge-verified { background: #4caf50; color: white; }
    .badge-unverified { background: #ff9800; color: white; }
    .badge-failed { background: #f44336; color: white; }
    .badge-active { background: #2196f3; color: white; }
    .badge-closed { background: #9e9e9e; color: white; }
    .badge-pending { background: #ff9800; color: white; }

    /* Timeline */
    .timeline-entry {
      position: relative;
      padding-left: 30px;
      margin: 0.15in 0;
      page-break-inside: avoid;
    }

    .timeline-entry::before {
      content: "●";
      position: absolute;
      left: 0;
      top: 0;
      font-size: 14pt;
      color: #1a1a1a;
    }

    .timeline-date {
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      color: #666;
      font-weight: bold;
    }

    .timeline-event {
      font-weight: bold;
      color: #1a1a1a;
    }

    .timeline-description {
      color: #555;
      font-size: 10pt;
      margin-top: 0.05in;
    }

    /* Footer */
    .report-footer {
      margin-top: 0.5in;
      padding-top: 0.2in;
      border-top: 2px solid #ccc;
      font-size: 8pt;
      color: #666;
      text-align: center;
    }

    /* Print Optimizations */
    @media print {
      body {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }

      .page {
        page-break-after: always;
      }

      h1, h2, h3 {
        page-break-after: avoid;
      }

      table, .info-box, .timeline-entry {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>

  <!-- ============================================================ -->
  <!-- COVER PAGE -->
  <!-- ============================================================ -->
  <div class="page cover-page">
    <div class="logo">JAIC</div>
    <div class="report-title">Investigational Brief</div>
    <div class="case-number">${data.caseNumber.full}</div>
    <div class="classification">${classification}</div>
    <div class="date-generated">Generated: ${formattedDate}</div>
    <div class="prepared-by">
      Prepared by<br>
      <strong>Jonathan Anderson Investigational Corporation</strong><br>
      Professional Investigational Services
    </div>
  </div>

  <!-- ============================================================ -->
  <!-- EXECUTIVE SUMMARY -->
  <!-- ============================================================ -->
  <div class="page">
    <h1>Executive Summary</h1>

    <h2>Case Overview</h2>
    <p>${escapeHTML(data.executiveSummary.overview)}</p>

    <h2>Key Findings</h2>
    <ul>
      ${data.executiveSummary.keyFindings.map(finding =>
        `<li>${escapeHTML(finding)}</li>`
      ).join('')}
    </ul>

    <h2>Recommendations</h2>
    <ul>
      ${data.executiveSummary.recommendations.map(rec =>
        `<li>${escapeHTML(rec)}</li>`
      ).join('')}
    </ul>
  </div>

  <!-- ============================================================ -->
  <!-- CASE DETAILS -->
  <!-- ============================================================ -->
  <div class="page">
    <h1>Case Details</h1>

    <div class="info-box">
      <strong>Case Number:</strong> ${data.caseNumber.full}<br>
      <strong>Case Title:</strong> ${escapeHTML(data.title)}<br>
      <strong>Domain:</strong> ${getCaseDomainLabel(data.domain)}<br>
      <strong>Status:</strong> <span class="badge badge-${data.status.toLowerCase()}">${data.status}</span><br>
      <strong>Intake Date:</strong> ${formatDate(data.intakeDate)}<br>
      <strong>Last Modified:</strong> ${formatDate(data.lastModified)}
      ${data.closedDate ? `<br><strong>Closed Date:</strong> ${formatDate(data.closedDate)}` : ''}
    </div>

    ${includeClientInfo && data.client ? `
    <h2>Client Information</h2>
    <div class="info-box">
      <strong>Client Name:</strong> ${escapeHTML(data.client.name)}<br>
      ${data.client.organization ? `<strong>Organization:</strong> ${escapeHTML(data.client.organization)}<br>` : ''}
      ${data.client.referenceNumber ? `<strong>Reference Number:</strong> ${escapeHTML(data.client.referenceNumber)}<br>` : ''}
      ${data.client.contactInfo ? `<strong>Contact:</strong> ${escapeHTML(data.client.contactInfo)}<br>` : ''}
    </div>
    ` : ''}
  </div>

  <!-- ============================================================ -->
  <!-- EVIDENCE SUMMARY -->
  <!-- ============================================================ -->
  ${includeEvidence && data.evidence.length > 0 ? `
  <div class="page">
    <h1>Evidence Summary</h1>

    <p>Total Evidence Items: <strong>${data.evidence.length}</strong></p>

    <table>
      <thead>
        <tr>
          <th>Evidence ID</th>
          <th>File Name</th>
          <th>Type</th>
          <th>Size</th>
          <th>Upload Date</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        ${data.evidence.map(item => `
        <tr>
          <td><span class="code">${item.id.substring(0, 12)}</span></td>
          <td>${escapeHTML(item.fileName)}</td>
          <td>${item.fileType}</td>
          <td>${formatFileSize(item.fileSize)}</td>
          <td>${formatDate(item.uploadDate)}</td>
          <td><span class="badge badge-${item.verificationStatus.toLowerCase()}">${item.verificationStatus}</span></td>
        </tr>
        `).join('')}
      </tbody>
    </table>

    <h2>Evidence Integrity Verification</h2>
    ${data.evidence.map(item => `
    <div class="info-box">
      <strong>File:</strong> ${escapeHTML(item.fileName)}<br>
      <strong>SHA-256 Hash:</strong> <span class="code">${item.hash}</span><br>
      <strong>Verification:</strong> <span class="badge badge-${item.verificationStatus.toLowerCase()}">${item.verificationStatus}</span>
      ${item.description ? `<br><strong>Description:</strong> ${escapeHTML(item.description)}` : ''}
    </div>
    `).join('')}
  </div>
  ` : ''}

  <!-- ============================================================ -->
  <!-- CHAIN OF CUSTODY -->
  <!-- ============================================================ -->
  ${includeChainOfCustody && data.chainOfCustody.length > 0 ? `
  <div class="page">
    <h1>Chain of Custody</h1>

    <div class="${custodyVerification.valid ? 'success-box' : 'error-box'}">
      <strong>Custody Chain Verification:</strong> ${custodyVerification.valid ? 'VALID ✓' : 'INVALID ✗'}
      ${!custodyVerification.valid ? `
        <br><strong>Errors Detected:</strong>
        <ul>
          ${custodyVerification.errors.map(err => `<li>${escapeHTML(err)}</li>`).join('')}
        </ul>
      ` : ''}
    </div>

    <p>Total Custody Events: <strong>${data.chainOfCustody.length}</strong></p>

    <table>
      <thead>
        <tr>
          <th>Entry ID</th>
          <th>Timestamp</th>
          <th>Action</th>
          <th>Actor</th>
          <th>Location</th>
          <th>Verification Hash</th>
        </tr>
      </thead>
      <tbody>
        ${data.chainOfCustody.map(entry => `
        <tr>
          <td><span class="code">${entry.id}</span></td>
          <td>${formatDateTime(entry.timestamp)}</td>
          <td><strong>${entry.action}</strong></td>
          <td>${escapeHTML(entry.actor)}</td>
          <td>${entry.location}</td>
          <td><span class="code">${entry.hash.substring(0, 16)}...</span></td>
        </tr>
        `).join('')}
      </tbody>
    </table>

    <h2>Detailed Custody Timeline</h2>
    ${data.chainOfCustody.map(entry => `
    <div class="timeline-entry">
      <div class="timeline-date">${formatDateTime(entry.timestamp)}</div>
      <div class="timeline-event">${entry.action} - ${escapeHTML(entry.actor)}</div>
      <div class="timeline-description">
        Evidence ID: ${entry.evidenceId} | Location: ${entry.location}<br>
        Verification Hash: <span class="code">${entry.hash}</span>
        ${entry.metadata ? `<br>Metadata: <span class="code">${JSON.stringify(entry.metadata)}</span>` : ''}
      </div>
    </div>
    `).join('')}
  </div>
  ` : ''}

  <!-- ============================================================ -->
  <!-- INVESTIGATIONAL TIMELINE -->
  <!-- ============================================================ -->
  ${includeTimeline && data.timeline.length > 0 ? `
  <div class="page">
    <h1>Investigational Timeline</h1>

    <p>Total Timeline Events: <strong>${data.timeline.length}</strong></p>

    ${data.timeline.map(event => `
    <div class="timeline-entry">
      <div class="timeline-date">${formatDateTime(event.timestamp)}</div>
      <div class="timeline-event">${escapeHTML(event.event)} [${event.category}]</div>
      <div class="timeline-description">
        Actor: ${escapeHTML(event.actor)}<br>
        ${escapeHTML(event.description)}
      </div>
    </div>
    `).join('')}
  </div>
  ` : ''}

  <!-- ============================================================ -->
  <!-- APPENDICES -->
  <!-- ============================================================ -->
  <div class="page">
    <h1>Appendices</h1>

    <h2>A. Technical Information</h2>
    <div class="info-box">
      <strong>Report Generated:</strong> ${new Date(generatedDate).toISOString()}<br>
      <strong>Generator Version:</strong> JAIC-PDF-GEN-v1.0.0<br>
      <strong>Report Format:</strong> HTML-to-PDF<br>
      <strong>Classification:</strong> ${classification}
    </div>

    <h2>B. Case Metadata</h2>
    <div class="info-box">
      <strong>Case Year:</strong> ${data.caseNumber.year}<br>
      <strong>Case Month:</strong> ${data.caseNumber.month}<br>
      <strong>Category Code:</strong> ${data.caseNumber.category}<br>
      <strong>Sequence Number:</strong> ${String(data.caseNumber.sequence).padStart(4, '0')}<br>
      <strong>Checksum:</strong> ${data.caseNumber.checksum}<br>
      ${data.metadata ? `<strong>Additional Metadata:</strong><br><pre class="code">${JSON.stringify(data.metadata, null, 2)}</pre>` : ''}
    </div>

    ${data.notes ? `
    <h2>C. Additional Notes</h2>
    <p>${escapeHTML(data.notes)}</p>
    ` : ''}

    <h2>D. Legal Disclaimers</h2>
    <div class="warning-box">
      This investigational brief is prepared as attorney work product and is confidential.
      It contains privileged information prepared for legal proceedings and is not for
      public distribution. Unauthorized disclosure may violate attorney-client privilege
      and work product protections.
    </div>

    <p><strong>Prepared by:</strong> Jonathan Anderson Investigational Corporation (JAIC)</p>
    <p><strong>Jurisdiction:</strong> Multi-jurisdictional investigational services</p>
    <p><strong>Standard:</strong> Professional investigational standards and forensic protocols</p>

    <div class="report-footer">
      <strong>Jonathan Anderson Investigational Corporation</strong><br>
      Professional Investigational Services | Attorney Work Product<br>
      This document was generated by the JAIC Investigational System<br>
      Case Number: ${data.caseNumber.full} | Generated: ${formattedDate}
    </div>
  </div>

</body>
</html>`;
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

function escapeHTML(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}

function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

function formatDateTime(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZoneName: 'short'
  });
}

function formatFileSize(bytes: number): string {
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  let size = bytes;
  let unitIndex = 0;

  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024;
    unitIndex++;
  }

  return `${size.toFixed(2)} ${units[unitIndex]}`;
}

function getCaseDomainLabel(domain: CaseDomain): string {
  const labels: Record<CaseDomain, string> = {
    FRAUD: 'Fraud & Financial Leakage',
    MISCONDUCT: 'Corporate Misconduct',
    CONTRACT: 'Contractual Noncompliance',
    ADMIN: 'Administrative Irregularities',
    DIGITAL: 'Digital Forensics',
    CROSSBORDER: 'Cross-Border Reconstructions',
    GENERAL: 'General Investigation',
  };
  return labels[domain];
}

// ============================================================================
// PDF GENERATION (PUPPETEER)
// ============================================================================

/**
 * Generate PDF report using Puppeteer
 * Requires: npm install puppeteer
 */
export async function generateInvestigationalReport(
  caseData: CaseData,
  options: ReportOptions = {}
): Promise<Buffer> {
  // Dynamic import to allow module to load even if puppeteer isn't installed
  let puppeteer;
  try {
    puppeteer = await import('puppeteer');
  } catch (error) {
    throw new Error(
      'Puppeteer is not installed. Run: npm install puppeteer\n' +
      'Error: ' + (error instanceof Error ? error.message : String(error))
    );
  }

  const html = generateHTMLReport(caseData, options);

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, {
      waitUntil: 'networkidle0'
    });

    const pdfBuffer = await page.pdf({
      format: 'letter',
      printBackground: true,
      margin: {
        top: '0.75in',
        right: '0.75in',
        bottom: '1in',
        left: '0.75in'
      },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 8pt; font-family: 'Courier New', monospace; width: 100%; padding: 0 0.75in; display: flex; justify-content: space-between; color: #666;">
          <span>${caseData.caseNumber.full}</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          <span>${new Date().toISOString().split('T')[0]}</span>
        </div>
      `
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

/**
 * Generate PDF filename for download
 */
export function generatePDFFilename(caseNumber: CaseNumber): string {
  const date = new Date().toISOString().split('T')[0].replace(/-/g, '');
  return `JAIC-${caseNumber.full}-Report-${date}.pdf`;
}

/**
 * Generate HTML report (for preview or alternative PDF generation)
 */
export function generateHTMLReportString(
  caseData: CaseData,
  options: ReportOptions = {}
): string {
  return generateHTMLReport(caseData, options);
}

/**
 * Validate case data before report generation
 */
export function validateCaseData(caseData: CaseData): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!caseData.caseNumber?.full) {
    errors.push('Case number is required');
  }

  if (!caseData.title?.trim()) {
    errors.push('Case title is required');
  }

  if (!caseData.executiveSummary?.overview?.trim()) {
    errors.push('Executive summary overview is required');
  }

  if (!caseData.executiveSummary?.keyFindings?.length) {
    errors.push('At least one key finding is required');
  }

  if (!caseData.executiveSummary?.recommendations?.length) {
    errors.push('At least one recommendation is required');
  }

  if (!caseData.intakeDate) {
    errors.push('Intake date is required');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

// ============================================================================
// EXPORT
// ============================================================================

export default {
  generateInvestigationalReport,
  generateHTMLReportString,
  generatePDFFilename,
  validateCaseData
};
